#!/usr/bin/env python
import matplotlib.pyplot as plt
import CodeTools.MethodsPyplot as mp
import CodeTools.vitools as vit

RootFolder  = "/Users/INAOE_Vital/Desktop/"
Pattern = "0445.fits"
PlotVector = None

#Find and organize files from terminal command or .py file
FilesList, PlotVector = mp.FindAndOrganize(PlotVector, Pattern, RootFolder)


#Generate plot frame and colors
Fig1, Axis1, Colors, PlotVector = mp.PlotFormat(PlotVector, 'Night')

#Loop through files
for i in range(len(FilesList)):
    plt.cla()
    #Store plot properties and command flags
    PlotVector = mp.PlotBackUp(PlotVector, 'Clean', None)                                   #Clean the non-constant part
    
    for j in range(len(FilesList[i])):
        CodeName, FileName, FileFolder, PlotVector = mp.FileAnalyzer(FilesList[i][j], PlotVector)
        x, y, ExtraData = mp.File2Data(FileFolder,FileName)
        
        X, Y, = mp.DataTreatment(x, y)
        
        Label = FileName[0:FileName.find('.')]
        PlotVector = mp.LinePlotter(Axis1, X, Y, Label, PlotVector, Colors[2][j])
        vit.SaveXYTable_2_Text(X, Y, FileFolder + FileName.replace('.fits','.dat'))
        
# Plot Format
    PlotVector = mp.TextFormat(Axis1, PlotVector, Colors,1,Plot_Title ='Sloan - WHT comparison')

# Save Plot 
#     plt.show()
    mp.PlotSaveManager(PlotVector,Colors, SavingFolder = FileFolder)   #Save PlotVector

    print i+1, '/' , len(FilesList)

#-----------------------------------------------------------------------------------------------------

print "All plots generated"


#Color_Vector = [BackgroundColor, ForegroundColor, PaletteColors]      
#                        0                1            2 (8 available)

# LEGEND String locations
# upper right        1
# upper left         2
# lower left         3
# lower right        4
# center right       5
# center left        6
# center right       7
# lower center       8    
# upper center       9
# center            10